language: node_js
node_js:
- node
before_script:
- npm install grunt-cli -g
env:
  global:
    secure: cMcnB1Z9RuN99ElVwoCmCfPmPmgFdcEzxR2BXbWfyI+Qm8GQI4rEq4+I35lgMBu47oePwRMkBnkw95cZTdlwrvTh6ZesgKMgU/MDSinf4Jd3O7IhawrjOjHGVesCEVLuP/o5CYPQvw/svNtm1mznIq8Wg8WZmpNFDVIgTF94jpwbR1ZfdfoNGlrXczXNL6U3Sj/2eTN+gW9JZ+utKp1/4iDcIJFayzZFsX58O5bH9yA0ofDIn7PywwoBwCKbHFL9VcwaHEBffKrFQYvjbA8hNlRhkggwIgcVj3fLrSMwcD58ZW+4oOJXSF6nKKTzGZIWGLzuoNQzTogOM/jODas0P0+RyFxkTFjNCSfwzILLRc9mcdEam/VAm1OHjPTB1yrD5qit5mNaa33ZMsxSx3OGQy6B+JmttpS4zxKhFGklfsh29X5HpDiaBb7FimO+dpkotyC7OkGKN6udGYhTa+qbTtGsA4Gh6XJpYXMTKhapRP6MWtRbhvvhDytsfqJ6homoKG6yUZQURkLaQbUm8yHS2cgGhfVMNJzut9cDVLNtZ5t/8L/esuAmR1FhZScbxlm1M6AXVKDUYz+Igt2mJGcoJX7ONVSe8gJ9Gqx/TY7qrx2Hq0Fw55XNaSBhxRxM+o+CK1ktgEjdXtB4NXbyv/SWjkrbdICwtG5170KoBjsgKak=
